name: "PR Merge into current Branch"

on:
  workflow_call:
    inputs:
      pr_number:
        required: false
        type: string
      github_repo:
        required: true
        type: string

jobs:
  merge_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check if triggered by PR
        id: check_pr
        run: |
          if [ -z "${{ inputs.pr_number }}"]; then
              echo "is_pr=false" >> $GITHUB_OUTPUT
              echo "ℹ️ Not a pull request event — skipping merge step."
              else
              echo "is_pr=true" >> $GITHUB_OUTPUT
              echo "✅ Pull request event detected (#${{ inputs.pr_number }})"
              fi
      
      - name: Check if PR is mergeable
        if: steps.check_pr.outputs.is_pr == 'true'
        id: mergeable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
            echo "Checking if PR #$PR_NUMBER is mergeable..."

            # Fetch PR info from GitHub API
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)

            mergeable=$(echo "$response" | jq -r '.mergeable')
            mergeable_state=$(echo "$response" | jq -r '.mergeable_state')

            echo "mergeable=$mergeable"
            echo "mergeable_state=$mergeable_state"

            if [ "$mergeable" != "true" ]; then
              echo "❌ Pull request has conflicts or is not mergeable (state: $mergeable_state)."
              exit 1
            fi

      - name: Merge Pull Request
        if: steps.mergeable.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
          echo "Merging PR #$PR_NUMBER..."
          gh auth setup-git
          gh auth status
          gh pr merge $PR_NUMBER --merge --admin
